version: '3'

services:
  # MySQL
  mysql:
    build: 
      dockerfile: ./deployments/docker/mysql/Dockerfile
      context: .
    container_name: mysql
    user: 1000:1000
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
    - ./mysql:/var/lib/mysql
    ports:
    - 3306:3306