output   = "dbmodels"
no-tests = true
wipe     = true
[mysql]
  dbname     = "react_catchup"
  host       = "localhost"
  port       = 3306
  user       = "root"
  pass       = "root"
  sslmode    = "false"